import ctypes

def add(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def sub(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def mul(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def tdiv(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def fdiv(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...

def eq(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def ne(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def gt(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def ge(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def lt(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def le(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...

def neg(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def pos(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def abs(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
