from typing import Tuple
import ctypes

def add(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def sub(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def mul(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def tdiv(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def fdiv(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def pow(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def mod(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...

def eq(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def ne(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def gt(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def ge(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def lt(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def le(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...

def neg(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def pos(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def abs(x:ctypes.c_void_p) -> ctypes.c_void_p: ...

def lshift(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def rshift(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...

def and_(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def nand_(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def or_(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def nor_(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def not_(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def xor_(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def xnor_(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
