from typing import Dict, List, Tuple, Any
import ctypes

# defined at ./tinytensor/engine/cuda/cuda.cu
def tocuda(pylist:List[Any], shape:Tuple[int,...], fmt:str, device_index:int) -> ctypes.c_void_p: ...
def tocpu(capsule:ctypes.c_void_p) -> ctypes.c_void_p: ...
def device_count() -> int: ...
def device_name(device:int) -> str: ...
def device_prop(device:int) -> Dict: ...
def is_available() -> bool: ...
def get_device() -> int: ...
