import ctypes
from typing import Any, Dict, Tuple

def tocuda(pyobj:Any, shape:Tuple[int,...], fmt:str, device_idx:int) -> ctypes.c_void_p: ...
def topyobj(capsule:ctypes.c_void_p) -> object: ...
def device_name(index:int) -> str: ...
def device_count() -> int: ...
def is_available() -> bool: ...
def get_device_prop() -> Dict: ...
def runtime_version() -> int: ...
def driver_version() -> int: ...
def driver_package() -> float: ...
def get_device() -> int: ...
