from typing import Optional, Tuple, overload
import ctypes

def add(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def sub(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def mul(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def tdiv(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def fdiv(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def pow(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def mod(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...

def eq(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def ne(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def gt(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def ge(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def lt(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def le(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...

def neg(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def pos(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def abs(x:ctypes.c_void_p) -> ctypes.c_void_p: ...

def rshift(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def lshift(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...

def and_(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def nand_(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def or_(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def nor_(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def not_(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def xor_(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def xnor_(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...

def permute(x:ctypes.c_void_p, axes:Tuple[int,...]) -> ctypes.c_void_p: ...

@overload
def sum(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
@overload
def sum(x:ctypes.c_void_p, axis:Optional[int]=None) -> ctypes.c_void_p: ...

def bmm(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...

def real(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def imag(x:ctypes.c_void_p) -> ctypes.c_void_p: ...

def log(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def log2(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def log10(x:ctypes.c_void_p) -> ctypes.c_void_p: ...

def exp(x:ctypes.c_void_p) -> ctypes.c_void_p: ...

def sin(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def cos(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def tan(x:ctypes.c_void_p) -> ctypes.c_void_p: ...

def asin(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def acos(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def atan(x:ctypes.c_void_p) -> ctypes.c_void_p: ...

def sinh(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def cosh(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def tanh(x:ctypes.c_void_p) -> ctypes.c_void_p: ...

def asinh(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def acosh(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
def atanh(x:ctypes.c_void_p) -> ctypes.c_void_p: ...

def sgn(x:ctypes.c_void_p) -> ctypes.c_void_p: ...
