import ctypes
from typing import Any, Tuple, Union

def tocpu(pyobj:Any, shape:Tuple[int,...], fmt:str) -> ctypes.c_void_p: ...
def topyobj(capsule:ctypes.c_void_p) -> object: ...
def ndim(capsule:ctypes.c_void_p) -> int: ...
def shape(capsule:ctypes.c_void_p) -> Tuple[int, ...]: ...
def stride(capsule:ctypes.c_void_p) -> Tuple[int, ...]: ...
def device(capsule:ctypes.c_void_p) -> Tuple[str, int]: ...
def dtype(capsule:ctypes.c_void_p) -> str: ...
def getitem(capsule:ctypes.c_void_p, index:Union[int,slice]) -> ctypes.c_void_p: ...
def empty(shape:Tuple[int, ...], fmt:str) -> ctypes.c_void_p: ...
