import ctypes

# defined at ./tinytensor/engine/cpu/cpu_ops.c
def add(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
def sub(x:ctypes.c_void_p, y:ctypes.c_void_p) -> ctypes.c_void_p: ...
